version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    ports:
      - "9930:8000"
    env_file:
      - .env
    networks:
      - proxy
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: "4G"
    restart: always

  worker:
    build:
      context: .
      dockerfile: docker/Dockerfile.api # Menggunakan Dockerfile yang sama, hanya command beda
    command: >
      celery -A app.tasks.celery_app worker
      -Q recognition --concurrency=2 --loglevel=info
    env_file:
      - .env
    networks:
      - proxy
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: "4G"
    restart: always

  flower:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    command: celery -A app.tasks.celery_app flower --port=5555
    ports:
      - "5555:5555"
    env_file:
      - .env
    networks:
      - proxy
    restart: always

networks:
  proxy:
    external: true
