"""Initial migration

Revision ID: 11584100a166
Revises: 
Create Date: 2026-05-11 10:11:09.603672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '11584100a166'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('faces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=False),
    sa.Column('image_path', sa.Text(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_faces_user_id', 'faces', ['user_id'], unique=False)
    
    # IVFFlat index for similarity search
    op.execute("""
        CREATE INDEX idx_faces_embedding 
        ON faces 
        USING ivfflat (embedding vector_cosine_ops) 
        WITH (lists = 64)
    """)

    op.create_table('recognition_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.String(length=100), nullable=True),
    sa.Column('matched_user_id', sa.UUID(), nullable=True),
    sa.Column('similarity', sa.Float(), nullable=True),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=True),
    sa.Column('input_image_path', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    op.create_index('idx_rec_results_job_id', 'recognition_results', ['job_id'], unique=False)
    op.create_index('idx_rec_results_matched_user', 'recognition_results', ['matched_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_rec_results_matched_user', table_name='recognition_results')
    op.drop_index('idx_rec_results_job_id', table_name='recognition_results')
    op.drop_table('recognition_results')
    op.drop_index('idx_faces_user_id', table_name='faces')
    op.drop_table('faces')
    # ### end Alembic commands ###
